export interface ContractTypeDefinition {
  slug: string
  hebrewName: string
  englishName: string
  defaultDepartment: string
  typicalObligations: string[]
  missingClauseRisks: string[]
  defaultRenewalMonths: number | null
  defaultNotifyBeforeDays: number
}

export const CONTRACT_TYPES: ContractTypeDefinition[] = [
  {
    slug: "service-agreement",
    hebrewName: "הסכם שירותים",
    englishName: "Service Agreement",
    defaultDepartment: "תפעול",
    typicalObligations: ["תשלום", "SLA", "תמיכה", "דיווח"],
    missingClauseRisks: ["הגבלת אחריות", "סודיות", "סיום התקשרות"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "sow",
    hebrewName: "SOW / נספח עבודה",
    englishName: "Statement of Work",
    defaultDepartment: "תפעול",
    typicalObligations: ["מסירת תוצר", "אבני דרך", "תשלום"],
    missingClauseRisks: ["היקף עבודה", "לוח זמנים", "קבלת עבודה"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 14,
  },
  {
    slug: "nda",
    hebrewName: "NDA / הסכם סודיות",
    englishName: "Non-Disclosure Agreement",
    defaultDepartment: "משפטי",
    typicalObligations: ["סודיות", "החזרת מידע"],
    missingClauseRisks: ["משך תקופת סודיות", "דין חל"],
    defaultRenewalMonths: 24,
    defaultNotifyBeforeDays: 60,
  },
  {
    slug: "employment",
    hebrewName: "הסכם העסקה",
    englishName: "Employment Agreement",
    defaultDepartment: "משאבי אנוש",
    typicalObligations: ["שכר", "תאריך תחילה", "סודיות", "קניין רוחני"],
    missingClauseRisks: ["אי-תחרות", "קניין רוחני", "סודיות"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "subcontractor",
    hebrewName: "הסכם קבלן משנה",
    englishName: "Subcontractor Agreement",
    defaultDepartment: "רכש",
    typicalObligations: ["תשלום", "מסירת תוצר", "ביטוח"],
    missingClauseRisks: ["שיפוי", "ביטוח", "הגבלת אחריות"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "vendor",
    hebrewName: "הסכם ספק",
    englishName: "Vendor Agreement",
    defaultDepartment: "רכש",
    typicalObligations: ["תשלום", "אספקה", "אחריות"],
    missingClauseRisks: ["אחריות מוצר", "תנאי החזרה", "ערבות"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "retainer",
    hebrewName: "הסכם ריטיינר",
    englishName: "Retainer Agreement",
    defaultDepartment: "כספים",
    typicalObligations: ["תשלום חודשי", "דיווח שעות", "חידוש"],
    missingClauseRisks: ["הגבלת שעות", "סיום התקשרות", "שינוי תעריף"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "saas-license",
    hebrewName: "הסכם SaaS / רישוי תוכנה",
    englishName: "SaaS / Software License",
    defaultDepartment: "טכנולוגיה / IT",
    typicalObligations: ["SLA", "תמיכה", "הגנת מידע", "חידוש"],
    missingClauseRisks: ["DPA", "SLA", "יציאה מהשירות", "גיבוי נתונים"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 60,
  },
  {
    slug: "partnership",
    hebrewName: "הסכם שותפות",
    englishName: "Partnership Agreement",
    defaultDepartment: "הנהלה",
    typicalObligations: ["חלוקת רווחים", "דיווח", "החלטות"],
    missingClauseRisks: ["יציאת שותף", "חלוקת רווחים", "סמכויות"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 60,
  },
  {
    slug: "distribution",
    hebrewName: "הסכם הפצה",
    englishName: "Distribution Agreement",
    defaultDepartment: "מכירות",
    typicalObligations: ["יעדי מכירה", "דיווח", "תשלום"],
    missingClauseRisks: ["בלעדיות", "טריטוריה", "סיום התקשרות"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 60,
  },
  {
    slug: "lease",
    hebrewName: "הסכם שכירות",
    englishName: "Lease Agreement",
    defaultDepartment: "נדל״ן / נכסים",
    typicalObligations: ["שכירות", "פיקדון", "חידוש", "תחזוקה"],
    missingClauseRisks: ["פיקדון", "הודעה מוקדמת", "ביטוח"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 90,
  },
  {
    slug: "property-management",
    hebrewName: "הסכם ניהול נכס",
    englishName: "Property Management Agreement",
    defaultDepartment: "נדל״ן / נכסים",
    typicalObligations: ["דמי ניהול", "דיווח", "תחזוקה"],
    missingClauseRisks: ["חובות מנהל", "ביטוח", "סיום"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 60,
  },
  {
    slug: "purchase",
    hebrewName: "הסכם רכישה",
    englishName: "Purchase Agreement",
    defaultDepartment: "רכש",
    typicalObligations: ["תשלום", "מסירה", "אחריות"],
    missingClauseRisks: ["אחריות", "החזרות", "כוח עליון"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 14,
  },
  {
    slug: "maintenance",
    hebrewName: "הסכם תחזוקה",
    englishName: "Maintenance Agreement",
    defaultDepartment: "תפעול",
    typicalObligations: ["SLA", "זמני תגובה", "תשלום"],
    missingClauseRisks: ["SLA", "חלקי חילוף", "כוח עליון"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "consulting",
    hebrewName: "הסכם ייעוץ",
    englishName: "Consulting Agreement",
    defaultDepartment: "הנהלה",
    typicalObligations: ["תשלום", "דיווח", "תוצרים"],
    missingClauseRisks: ["הגבלת אחריות", "סודיות", "קניין רוחני"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 14,
  },
  {
    slug: "loan",
    hebrewName: "הסכם הלוואה",
    englishName: "Loan Agreement",
    defaultDepartment: "כספים",
    typicalObligations: ["החזר", "ריבית", "ערבות"],
    missingClauseRisks: ["בטוחות", "אירוע כשל", "פירעון מוקדם"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "brokerage",
    hebrewName: "הסכם תיווך",
    englishName: "Brokerage Agreement",
    defaultDepartment: "מכירות",
    typicalObligations: ["עמלה", "בלעדיות", "דיווח"],
    missingClauseRisks: ["בלעדיות", "תקופה", "עמלה"],
    defaultRenewalMonths: 6,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "termination",
    hebrewName: "הסכם סיום התקשרות",
    englishName: "Termination Agreement",
    defaultDepartment: "משפטי",
    typicalObligations: ["תשלום סופי", "החזרת מידע", "סודיות"],
    missingClauseRisks: ["ויתור הדדי", "סודיות", "תשלום"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 7,
  },
  {
    slug: "framework",
    hebrewName: "הסכם מסגרת",
    englishName: "Framework Agreement",
    defaultDepartment: "רכש",
    typicalObligations: ["תנאי מסגרת", "הזמנות", "חידוש"],
    missingClauseRisks: ["תנאי שינוי מחיר", "יציאה", "מינימום"],
    defaultRenewalMonths: 24,
    defaultNotifyBeforeDays: 60,
  },
  {
    slug: "work-order",
    hebrewName: "הזמנת עבודה",
    englishName: "Work Order",
    defaultDepartment: "תפעול",
    typicalObligations: ["אספקה", "תשלום", "קבלה"],
    missingClauseRisks: ["לוח זמנים", "תנאי קבלה"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 7,
  },
  {
    slug: "sales",
    hebrewName: "הסכם מכר",
    englishName: "Sales Agreement",
    defaultDepartment: "מכירות",
    typicalObligations: ["תשלום", "מסירה", "אחריות"],
    missingClauseRisks: ["אחריות", "החזרות", "פיצוי"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 14,
  },
  {
    slug: "investment",
    hebrewName: "הסכם מניות / השקעה",
    englishName: "Investment / Shareholders Agreement",
    defaultDepartment: "הנהלה",
    typicalObligations: ["דיווח", "החלטות דירקטוריון", "חלוקת רווחים"],
    missingClauseRisks: ["אנטי דילול", "Tag Along", "דין חל"],
    defaultRenewalMonths: null,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "customer-service",
    hebrewName: "הסכם שירות לקוחות",
    englishName: "Customer Service Agreement",
    defaultDepartment: "שירות לקוחות",
    typicalObligations: ["SLA", "זמני תגובה", "דיווח"],
    missingClauseRisks: ["SLA", "פיצוי", "סיום"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 30,
  },
  {
    slug: "dpa",
    hebrewName: "הסכם אבטחת מידע / DPA",
    englishName: "Data Processing Agreement",
    defaultDepartment: "אבטחת מידע",
    typicalObligations: ["אבטחת מידע", "דיווח אירועים", "מחיקת נתונים"],
    missingClauseRisks: ["תת-מעבד", "העברת מידע", "מחיקה"],
    defaultRenewalMonths: 12,
    defaultNotifyBeforeDays: 60,
  },
]

export const CONTRACT_TYPE_MAP = new Map(
  CONTRACT_TYPES.map((t) => [t.slug, t])
)

export function getContractTypeOptions() {
  return CONTRACT_TYPES.map((t) => ({
    value: t.slug,
    label: t.hebrewName,
  }))
}
