import type { AuditLog } from '@/lib/types';
import { ORG_ID } from './organizations';
import { USER_IDS } from './users';
import { CONTRACT_IDS } from './contracts';
import { DEAL_IDS } from './deals';
import { COMPANY_IDS } from './companies';

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'aud_clx8kea0v0097qr5g1a2b3c4d',
    organizationId: ORG_ID,
    userId: USER_IDS.shai,
    action: 'create',
    actionLabel: 'יצירת חוזה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.solarService,
    entityName: 'הסכם שירותים - התקנת מערכת סולארית',
    details: 'נוצר הסכם שירותים חדש עבור סולאר פאנל ישראל',
    ipAddress: '185.46.212.88',
    createdAt: '2025-01-15T09:00:00.000Z',
  },
  {
    id: 'aud_clx8keb0v0098qr5g5e6f7g8h',
    organizationId: ORG_ID,
    userId: USER_IDS.merav,
    action: 'update',
    actionLabel: 'עדכון חוזה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.solarService,
    entityName: 'הסכם שירותים - התקנת מערכת סולארית',
    details: 'עדכון תנאי תשלום וסעיפי אחריות - גרסה 2',
    ipAddress: '185.46.212.90',
    createdAt: '2025-02-10T14:00:00.000Z',
  },
  {
    id: 'aud_clx8kec0v0099qr5g9i0j1k2l',
    organizationId: ORG_ID,
    userId: USER_IDS.shai,
    action: 'approve',
    actionLabel: 'אישור חוזה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.solarService,
    entityName: 'הסכם שירותים - התקנת מערכת סולארית',
    details: 'אישור סופי להסכם לאחר בדיקה משפטית',
    ipAddress: '185.46.212.88',
    createdAt: '2025-02-25T11:00:00.000Z',
  },
  {
    id: 'aud_clx8ked0v0100qr5g3m4n5o6p',
    organizationId: ORG_ID,
    userId: USER_IDS.shai,
    action: 'sign',
    actionLabel: 'חתימת חוזה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.solarService,
    entityName: 'הסכם שירותים - התקנת מערכת סולארית',
    details: 'חתימה דיגיטלית על ההסכם',
    ipAddress: '185.46.212.88',
    createdAt: '2025-02-28T10:00:00.000Z',
  },
  {
    id: 'aud_clx8kee0v0101qr5g7q8r9s0t',
    organizationId: ORG_ID,
    userId: USER_IDS.merav,
    action: 'create',
    actionLabel: 'יצירת עסקה',
    entityType: 'deal',
    entityId: DEAL_IDS.digitalCampaign,
    entityName: 'קמפיין דיגיטלי שנתי - ניהול מדיה',
    details: 'יצירת עסקה חדשה עם דיגיטל מדיה גרופ',
    ipAddress: '185.46.212.90',
    createdAt: '2025-04-01T09:00:00.000Z',
  },
  {
    id: 'aud_clx8kef0v0102qr5g1u2v3w4x',
    organizationId: ORG_ID,
    userId: USER_IDS.ori,
    action: 'create',
    actionLabel: 'יצירת חוזה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.fintechConsulting,
    entityName: 'הסכם ייעוץ - פיתוח פלטפורמת תשלומים',
    details: 'הכנת טיוטה ראשונה להסכם ייעוץ עם אלפא פינטק',
    ipAddress: '185.46.212.92',
    createdAt: '2025-06-01T11:00:00.000Z',
  },
  {
    id: 'aud_clx8keg0v0103qr5g5y6z7a8b',
    organizationId: ORG_ID,
    userId: USER_IDS.shai,
    action: 'comment',
    actionLabel: 'הוספת הערה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.fintechConsulting,
    entityName: 'הסכם ייעוץ - פיתוח פלטפורמת תשלומים',
    details: 'הוספת הערות לסעיפי קניין רוחני ותשלום',
    ipAddress: '185.46.212.88',
    createdAt: '2025-06-05T15:00:00.000Z',
  },
  {
    id: 'aud_clx8keh0v0104qr5g9c0d1e2f',
    organizationId: ORG_ID,
    userId: USER_IDS.noa,
    action: 'create',
    actionLabel: 'יצירת חברה',
    entityType: 'company',
    entityId: COMPANY_IDS.medixHealth,
    entityName: 'מדיקס בריאות דיגיטלית',
    details: 'הוספת חברת מדיקס למערכת',
    ipAddress: '185.46.212.94',
    createdAt: '2025-03-01T08:00:00.000Z',
  },
  {
    id: 'aud_clx8kei0v0105qr5g3g4h5i6j',
    organizationId: ORG_ID,
    userId: USER_IDS.merav,
    action: 'send',
    actionLabel: 'שליחת חוזה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.migdalService,
    entityName: 'הסכם שירותים - תחזוקת מערכת ביטוח',
    details: 'שליחת ההסכם לאישור מיכל פרץ ממגדל ביטוח',
    ipAddress: '185.46.212.90',
    createdAt: '2025-06-10T15:30:00.000Z',
  },
  {
    id: 'aud_clx8kej0v0106qr5g7k8l9m0n',
    organizationId: ORG_ID,
    userId: USER_IDS.ori,
    action: 'upload',
    actionLabel: 'העלאת מסמך',
    entityType: 'contract',
    entityId: CONTRACT_IDS.cloudService,
    entityName: 'הסכם שירותי ענן - מיגרציה ותשתיות',
    details: 'העלאת נספח טכני מעודכן - ארכיטקטורת ענן',
    ipAddress: '185.46.212.92',
    createdAt: '2025-05-20T14:00:00.000Z',
  },
  {
    id: 'aud_clx8kek0v0107qr5g1o2p3q4r',
    organizationId: ORG_ID,
    userId: USER_IDS.shai,
    action: 'export',
    actionLabel: 'ייצוא חוזה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.solarService,
    entityName: 'הסכם שירותים - התקנת מערכת סולארית',
    details: 'ייצוא ההסכם לפורמט PDF',
    ipAddress: '185.46.212.88',
    createdAt: '2025-03-02T09:00:00.000Z',
  },
  {
    id: 'aud_clx8kel0v0108qr5g5s6t7u8v',
    organizationId: ORG_ID,
    userId: USER_IDS.tamar,
    action: 'archive',
    actionLabel: 'העברה לארכיון',
    entityType: 'contract',
    entityId: CONTRACT_IDS.solarEmployment,
    entityName: 'חוזה העסקה - מהנדס פרויקטים בכיר',
    details: 'העברת חוזה העסקה שפג תוקפו לארכיון',
    ipAddress: '185.46.212.96',
    createdAt: '2025-06-02T10:00:00.000Z',
  },
  {
    id: 'aud_clx8kem0v0109qr5g9w0x1y2z',
    organizationId: ORG_ID,
    userId: USER_IDS.merav,
    action: 'reject',
    actionLabel: 'דחיית חוזה',
    entityType: 'contract',
    entityId: CONTRACT_IDS.digitalSales,
    entityName: 'הסכם מכירות - חבילת פרסום דיגיטלי',
    details: 'דחיית הטיוטה הראשונה - נדרשים תיקונים בסעיפי התשלום',
    ipAddress: '185.46.212.90',
    createdAt: '2025-06-13T11:00:00.000Z',
  },
];
