import type { Clause } from '@/lib/types';
import { ORG_ID } from './organizations';
import { USER_IDS } from './users';

export const mockClauses: Clause[] = [
  {
    id: 'cls_clx8kaa0v0068qr5g1a2b3c4d',
    organizationId: ORG_ID,
    title: 'סעיף סודיות סטנדרטי',
    content:
      'כל צד מתחייב לשמור בסודיות מוחלטת כל מידע שיימסר לו על ידי הצד השני במסגרת הסכם זה, ולא לעשות בו כל שימוש שאינו לצורך ביצוע ההסכם, וזאת למשך תקופה של 3 שנים מתום ההסכם.',
    category: 'confidentiality',
    tags: ['סודיות', 'סטנדרטי'],
    isFavorite: true,
    usageCount: 32,
    createdById: USER_IDS.shai,
    createdAt: '2024-06-15T10:00:00.000Z',
    updatedAt: '2025-05-01T09:00:00.000Z',
  },
  {
    id: 'cls_clx8kab0v0069qr5g5e6f7g8h',
    organizationId: ORG_ID,
    title: 'סעיף הגבלת אחריות',
    content:
      'אחריותו הכוללת של נותן השירותים על פי הסכם זה לא תעלה על סכום התמורה ששולמה בפועל במהלך 12 החודשים שקדמו לאירוע המזכה בפיצוי. בשום מקרה לא יהיה נותן השירותים אחראי לנזקים עקיפים, תוצאתיים או מיוחדים.',
    category: 'liability',
    tags: ['אחריות', 'הגבלה'],
    isFavorite: true,
    usageCount: 28,
    createdById: USER_IDS.shai,
    createdAt: '2024-06-15T10:30:00.000Z',
    updatedAt: '2025-04-15T11:00:00.000Z',
  },
  {
    id: 'cls_clx8kac0v0070qr5g9i0j1k2l',
    organizationId: ORG_ID,
    title: 'סעיף תנאי תשלום - שוטף + 30',
    content:
      'התשלום יבוצע כנגד חשבונית מס כדין, בתוך 30 יום מתום החודש בו הוצאה החשבונית. איחור בתשלום יישא ריבית פיגורים בשיעור של 1.5% לחודש או החלק היחסי ממנו.',
    category: 'payment',
    tags: ['תשלום', 'שוטף+30'],
    isFavorite: true,
    usageCount: 45,
    createdById: USER_IDS.merav,
    createdAt: '2024-07-01T09:00:00.000Z',
    updatedAt: '2025-05-20T14:00:00.000Z',
  },
  {
    id: 'cls_clx8kad0v0071qr5g3m4n5o6p',
    organizationId: ORG_ID,
    title: 'סעיף כוח עליון',
    content:
      'אף צד לא יישא באחריות לאי-קיום התחייבויותיו על פי הסכם זה, אם אי-הקיום נגרם עקב נסיבות שמעבר לשליטתו הסבירה, לרבות מלחמה, שביתה, מגיפה, אסון טבע, או צו של רשות מוסמכת. הצד הנפגע יודיע לצד השני בהקדם האפשרי על קרות אירוע כוח עליון.',
    category: 'force_majeure',
    tags: ['כוח עליון', 'פטור'],
    isFavorite: false,
    usageCount: 15,
    createdById: USER_IDS.shai,
    createdAt: '2024-07-10T11:00:00.000Z',
    updatedAt: '2025-03-01T10:00:00.000Z',
  },
  {
    id: 'cls_clx8kae0v0072qr5g7q8r9s0t',
    organizationId: ORG_ID,
    title: 'סעיף סיום הסכם',
    content:
      'כל צד רשאי לסיים הסכם זה במתן הודעה בכתב של 30 יום מראש. במקרה של הפרה יסודית, הצד הנפגע רשאי לסיים את ההסכם לאלתר בהודעה בכתב, ובלבד שניתנה לצד המפר הזדמנות סבירה לתקן את ההפרה בתוך 14 ימי עסקים.',
    category: 'termination',
    tags: ['סיום', 'הפרה'],
    isFavorite: true,
    usageCount: 22,
    createdById: USER_IDS.merav,
    createdAt: '2024-07-15T13:00:00.000Z',
    updatedAt: '2025-04-01T09:00:00.000Z',
  },
  {
    id: 'cls_clx8kaf0v0073qr5g1u2v3w4x',
    organizationId: ORG_ID,
    title: 'סעיף קניין רוחני',
    content:
      'כל זכויות הקניין הרוחני בתוצרי העבודה שיפותחו במסגרת הסכם זה יהיו בבעלות הלקוח, למעט כלים ומתודולוגיות שהיו בבעלות נותן השירותים קודם לתחילת ההסכם. נותן השירותים מעניק ללקוח רישיון בלתי הדיר לשימוש בכלים אלו.',
    category: 'ip',
    tags: ['קניין רוחני', 'בעלות'],
    isFavorite: false,
    usageCount: 19,
    createdById: USER_IDS.ori,
    createdAt: '2024-08-01T10:00:00.000Z',
    updatedAt: '2025-05-10T12:00:00.000Z',
  },
  {
    id: 'cls_clx8kag0v0074qr5g5y6z7a8b',
    organizationId: ORG_ID,
    title: 'סעיף שיפוי',
    content:
      'נותן השירותים ישפה ויגן על הלקוח מפני כל תביעה, דרישה, הפסד או נזק הנובעים מהפרת מצגי נותן השירותים בהסכם זה, לרבות הפרת זכויות קניין רוחני של צד שלישי.',
    category: 'indemnification',
    tags: ['שיפוי', 'הגנה'],
    isFavorite: false,
    usageCount: 14,
    createdById: USER_IDS.ori,
    createdAt: '2024-08-15T14:00:00.000Z',
    updatedAt: '2025-03-20T10:00:00.000Z',
  },
  {
    id: 'cls_clx8kah0v0075qr5g9c0d1e2f',
    organizationId: ORG_ID,
    title: 'סעיף יישוב סכסוכים',
    content:
      'כל סכסוך הנובע מהסכם זה או הקשור אליו יועבר תחילה לגישור בפני מגשר מוסכם. אם הגישור לא יניב פתרון בתוך 30 יום, יועבר הסכסוך לבוררות בפני בורר דן יחיד בהתאם לחוק הבוררות, תשכ"ח-1968. מקום הבוררות יהיה תל אביב.',
    category: 'dispute_resolution',
    tags: ['סכסוכים', 'בוררות', 'גישור'],
    isFavorite: false,
    usageCount: 11,
    createdById: USER_IDS.shai,
    createdAt: '2024-09-01T09:00:00.000Z',
    updatedAt: '2025-02-10T15:00:00.000Z',
  },
  {
    id: 'cls_clx8kai0v0076qr5g3g4h5i6j',
    organizationId: ORG_ID,
    title: 'סעיף כללי - דין חל וסמכות שיפוט',
    content:
      'על הסכם זה יחולו דיני מדינת ישראל. סמכות השיפוט הבלעדית לכל עניין הנובע מהסכם זה מוקנית לבתי המשפט המוסמכים בתל אביב-יפו.',
    category: 'general',
    tags: ['כללי', 'דין חל', 'סמכות שיפוט'],
    isFavorite: true,
    usageCount: 40,
    createdById: USER_IDS.shai,
    createdAt: '2024-06-15T10:15:00.000Z',
    updatedAt: '2025-01-15T08:00:00.000Z',
  },
  {
    id: 'cls_clx8kaj0v0077qr5g7k8l9m0n',
    organizationId: ORG_ID,
    title: 'סעיף אי-תחרות',
    content:
      'העובד מתחייב כי במשך תקופה של 12 חודשים לאחר סיום העסקתו, לא יעבוד ולא ייתן שירותים לכל גורם המתחרה ישירות בעסקי המעסיק, ולא ישדל לקוחות או עובדים של המעסיק.',
    category: 'general',
    tags: ['אי-תחרות', 'העסקה'],
    isFavorite: false,
    usageCount: 9,
    createdById: USER_IDS.merav,
    createdAt: '2024-10-01T11:00:00.000Z',
    updatedAt: '2025-04-05T10:00:00.000Z',
  },
];
